apiVersion: apps/v1
kind: Deployment
metadata:   
  name: nginx
  namespace: bbl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nginx
       
    spec:
      containers:     
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: metrics          
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/conf.d       
      restartPolicy: Always      
      volumes:
      # - name: www-storage
      #   persistentVolumeClaim:
      #     claimName: app-pvc      
      - name: nginx-config-volume
        configMap:
          name: nginx-config
      