# Deployment pour le service Jolie
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jolie-adaptation-service
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jolie-adaptation
  template:
    metadata:
      labels:
        app: jolie-adaptation
    spec:
      serviceAccountName: jolie-adaptation-sa
      imagePullSecrets:
      - name: regcred
      containers:
      - name: jolie-adaptation
        image: pjoseph5011/adaptation-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: PROMETHEUS_URL
          value: "http://bibliobservability-kube-pr-prometheus.monitoring.svc.cluster.local:9090"
        - name: KEDA_URL
          value: "http://keda-operator.keda:8080"
        - name: KUBERNETES_SERVICE_HOST
          value: "kubernetes.default.svc.cluster.local"
        - name: KUBERNETES_SERVICE_PORT
          value: "443"
---
# Service pour exposer Jolie
apiVersion: v1
kind: Service
metadata:
  name: jolie-adaptation-service
  namespace: monitoring
spec:
  selector:
    app: jolie-adaptation
  ports:
  - port: 8088
    targetPort: 8088
  type: ClusterIP
---
# RBAC pour permettre à Jolie d'interagir avec l'API Kubernetes
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jolie-adaptation-sa
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jolie-adaptation-role
  namespace: monitoring
rules:
- apiGroups: [ "keda.sh" ]
  resources: [ "scaledobjects" ]
  verbs: [ "get", "list", "watch", "patch" ]
- apiGroups: [ "" ]
  resources: [ "pods", "services" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jolie-adaptation-binding
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: jolie-adaptation-role
subjects:
- kind: ServiceAccount
  name: jolie-adaptation-sa
  namespace: monitoring
---
# Configuration des règles de surveillance personnalisées
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: jolie-adaptation-rules
  namespace: monitoring
spec:
  groups:
  - name: jolie.rules
    rules:
    - record: service_adaptation_score
      expr: |
        (
          rate(http_requests_total[5m]) * 0.7 +
          rate(mysql_slow_queries[5m]) * 0.3
        ) / on(service) group_left max(service_capacity)
