global:
route:
  group_by: [ 'alertname', 'job', 'instance', 'severity' ]
  group_wait: 1s
  group_interval: 5s
  repeat_interval: 1m
  receiver: "jolie-webhook"

receivers:
- name: "jolie-webhook"
  webhook_configs:
  - url: "http://jolie-proxy:9092/alert"
    send_resolved: false
