apiVersion: v1
kind: Namespace
metadata:
  name: bbl
  labels:
    name: bbl
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
---
apiVersion: v1
kind: Namespace
metadata:
  name: keda
  labels:
    name: keda
