apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-pv
  namespace: bbl
spec:
  storageClassName: app-sc
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 30Mi
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /var/www/html
