apiVersion: apps/v1
kind: Deployment
metadata:
  name: biblio-api
  namespace: bbl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: biblio-api
  template:
    metadata:
      labels:
        app: biblio-api
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: biblio-api
        image: pjoseph5011/kubescale_api:latest      
        imagePullPolicy: Always    #IfNotPresent        
        volumeMounts:
        - name: prometheus-dir
          mountPath: /tmp
        ports:
        - containerPort: 5001
          name: metrics
        command: ['python3', 'api.py']
      volumes:
      - name: prometheus-dir
        emptyDir: {}
       