apiVersion: v1
kind: Service
metadata:
  name: biblio-api
  namespace: bbl
spec:
  selector:
    app: biblio-api
  ports:
  - port: 5001
    protocol: TCP
    name: metrics
    targetPort: 5001
  type: ClusterIP
  