include "console.iol"
include "time.iol"
include "database.iol"
include "jolie-proxy-interface.iol"
include "runtime.iol"

// 📌 Service JolieProxy
service JolieProxy {
    execution { concurrent }
    
    // 🔗 Connexion MySQL avec gestion des tentatives
    define initializeMySQLConnection
    {
        scope( connection ) {
            install( ConnectionError =>
                connectionAttempt++;
                if ( connectionAttempt > 3 ) {
                    println@Console("❌ Impossible de se connecter à MySQL après 3 tentatives.")()
                    global.mysqlAvailable = false
                    throw( ConnectionError )
                } else {
                    println@Console("⏳ Tentative " + connectionAttempt + " de connexion à MySQL...")()
                    sleep@Time( connectionAttempt * 1500 )();
                    initializeMySQLConnection

                }
            )
            with( connectionInfo ) {
                .username = "root";
                .port = 3306;
                .password = "password";
                .host = "mysql";
                .database = "gestion_bibliotheque"; 
                .driver = "mysql"
                .checkConnection = 1;
                .toLowerCase = true
            };
            connect@Database( connectionInfo )();
            println@Console("✅ Connexion MySQL établie.")()
            global.mysqlAvailable = true
            
        }
    }

    // 🔗 Connexion HSQLDB Embedded
    define initializeHSQLDBConnection {
        scope( hsqldbConnection ) {
            install( HSQLDBError =>
                println@Console("❌ Impossible de se connecter à HSQLDB.")();
                global.hsqldbAvailable = false
                throw( HSQLDBError )
            );
            
            with (connectionInfo) {
                .username = "sa";
                .password = "";
                .host = "";
                .database = "file:bibliodb/bibliodb"; // Pour stockage persistant
                .driver = "hsqldb_embedded"
            };
            connect@Database(connectionInfo)();
            println@Console("✅ Connexion HSQLDB établie.")();
            global.hsqldbAvailable = true
        };
        // create table if it does not exist
        scope ( createTable ) {
            install ( SQLException => println@Console("Books table already there" + SQLException)() );
            updateRequest =
                "CREATE TABLE books (
                    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "title VARCHAR(255) NOT NULL, " +
                    "ISBN VARCHAR(255) NOT NULL, " +
                    "user_id VARCHAR(255) NOT NULL, " +
                    "reservation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP" +
                ")";
            update@Database( updateRequest )( ret )
        };
        scope ( insertIntoTable) {
            install ( SQLException => println@Console("Books already inserted" + SQLException)() );

            updateRequest = "INSERT INTO books (title, ISBN, user_id) VALUES ('Le Petit Prince', '978-2-266-11111-1', '1');"; 
            update@Database( updateRequest )( ret )
            updateRequest = "INSERT INTO books (title, ISBN, user_id) VALUES ('Le Seigneur des Anneaux', '978-2-266-11111-2', '2');";
            update@Database( updateRequest )( ret )
            updateRequest = "INSERT INTO books (title, ISBN, user_id) VALUES ('Harry Potter', '978-2-266-11111-3', '3');";
            update@Database( updateRequest )( ret )
            updateRequest = "INSERT INTO books (title, ISBN, user_id) VALUES ('Les Misérables', '978-2-266-11111-4', '4');";
            update@Database( updateRequest )( ret )
            updateRequest = "INSERT INTO books (title, ISBN, user_id) VALUES ('Les Trois Mousquetaires', '978-2-266-11111-5', '5');";
            update@Database( updateRequest )( ret )
            updateRequest = "INSERT INTO books (title, ISBN, user_id) VALUES ('Les Fleurs du Mal', '978-2-266-11111-6', '6');";
            update@Database( updateRequest )( ret )
            updateRequest = "INSERT INTO books (title, ISBN, user_id) VALUES ('Les Contemplations', '978-2-266-11111-7', '7');";
            update@Database( updateRequest )( ret )
            
        }
    }
                



    // ✅ Réception des alertes Prometheus via Alertmanager
    inputPort AlertPort {
        location: "socket://0.0.0.0:9092"
        protocol: http {
            format = "json"
        }
        Interfaces: AlertInterface
    }

    // ✅ Proxy API pour FastAPI
    inputPort ProxyPort {
        location: "socket://0.0.0.0:9091"
        protocol: http {
            format = "json"
        }
        Interfaces: ProxyInterface, 
                    AlertInterface
    }

    // ✅ Exposition des métriques pour Prometheus
    inputPort MetricsPort {
        location: "socket://0.0.0.0:9191/metrics"
        protocol: http {
            format = "raw"
        }
        Interfaces: ProxyInterface
    }

    // 🔗 Connexion à MySQL et HSQLDB au démarrage
    init {
        // 🔍 Variable globale pour suivre l'état des bases de données
        global.mysqlAvailable = true
        global.hsqldbAvailable = true
        getenv@Runtime( "HOSTNAME" )( HOSTNAME )

        initializeMySQLConnection
        if(!global.mysqlAvailable) {
            initializeHSQLDBConnection
        }
        
    }

    // ✅ Logique principale
    main {       
        // 🔔 Gestion des alertes de Prometheus
        [ alert(request)() {
            println@Console("🔔 Alerte reçue : " + request.alerts[0].labels.alertname)();
            if (request.status == "firing") {
                if (request.alerts[0].labels.alertname == "MySQL_Down") {
                    if (global.mysqlAvailable) {
                        global.mysqlAvailable = false;
                        initializeHSQLDBConnection
                        println@Console("🔴 MySQL est hors service. Basculement sur HSQLDB.")()
                    }
                }
                if (request.alerts[0].labels.alertname == "MySQL_Up") {
                    if(!global.mysqlAvailable) {
                        global.mysqlAvailable = true;
                        initializeMySQLConnection
                        println@Console("✅ MySQL est de retour en ligne.")()
                    }
                }
                
            }
        }] { nullProcess }

        // 📌 Réservation d'un livre
        [ reserveBook(request)(response) {
            if (global.mysqlAvailable) {
                scope(sqlTransaction) {
                    install(SQLException => {
                        response.status = "ERROR";
                        response.error = "Erreur SQL: " + SQLException;
                        println@Console("❌ Erreur lors de l'insertion MySQL: " + SQLException)()
                    });
                    updateRequest = "INSERT INTO Reservations (eventId, userId) VALUES (:eventId, :userId)";
                    updateRequest.eventId = request.eventId;
                    updateRequest.userId = request.userId;
                    update@Database(updateRequest)(dbResponse);
                    response.status = "RESERVED"
                }
            } else if (global.hsqldbAvailable) {
                println@Console("⚠️ MySQL indisponible, basculement sur HSQLDB.")();
                updateRequest = "INSERT INTO Reservations (eventId, userId) VALUES (:eventId, :userId)";
                updateRequest.eventId = request.eventId;
                updateRequest.userId = request.userId;
                update@Database(updateRequest)(dbResponse);
                response.status = "RESERVED (HSQLDB)"
            } else {
                response.status = "ERROR";
                response.error = "Aucune base de données disponible (MySQL et HSQLDB hors ligne)"
            }
        }] { nullProcess }

        // 📌 Récupération des livres
        [ getBooks()(response) {
            if (global.mysqlAvailable) {
                scope(sqlQuery) {
                    install(SQLException => {
                        response.status = "ERROR";
                        response.error = "Erreur SQL: " + SQLException;
                        println@Console("❌ Erreur lors de la récupération des livres MySQL: " + SQLException)()
                    });
                    query@Database("SELECT * FROM books;")(sqlResponse);
                    println@Console("📚 Livres récupérés depuis MySQL." + sqlResponse)()
                    response -> sqlResponse
                }
            } else if (global.hsqldbAvailable) {                
                query@Database("SELECT * FROM books;")(sqlResponse);
                println@Console("📚 Livres récupérés depuis HSQLDB." + sqlResponse)()
                response -> sqlResponse                
            } else {
                response.status = "ERROR";
                response.error = "Aucune base de données disponible (MySQL et HSQLDB hors ligne)"
            }
        }] { nullProcess }

        // 📊 Fournir les métriques à Prometheus
        [ metrics()(response) {
            println@Console("📊 Envoi des métriques à Prometheus.")();
            if (global.mysqlAvailable) {
                response = "jolie_mysql_status 1\n"
            } else {
                response = "jolie_mysql_status 0\n"
            }
            
        }] { nullProcess }
    }
}
