apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-initdb-config
  namespace: bbl
data:
  init.sql: |
    -- Création de la base de données
    CREATE DATABASE IF NOT EXISTS gestion_bibliotheque;

    -- Utilisation de la base de données
    USE gestion_bibliotheque;

    CREATE TABLE books (
    id INT AUTO_INCREMENT PRIMARY KEY,
    ISBN VARCHAR(255) NOT NULL,
    user_id VARCHAR(255) NOT NULL,
    reservation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

    CREATE TABLE users (
        id INT AUTO_INCREMENT PRIMARY KEY,
        user_id VARCHAR(255) NOT NULL,
        user_name VARCHAR(255) NOT NULL,
        user_email VARCHAR(255) NOT NULL
    );
    insert into users (user_id, user_name, user_email) values ('1', 'Pierre', 'joseph@pierrecom');
    insert into users (user_id, user_name, user_email) values ('2', 'Jean', 'jean@pierrecom');
    insert into users (user_id, user_name, user_email) values ('3', 'Paul', 'paul@pierrecom');
    insert into users (user_id, user_name, user_email) values ('4', 'Jacques', 'jacques@pierrecom');

    insert into books (ISBN, user_id) values ('123456789', '1');
    insert into books (ISBN, user_id) values ('987654321', '2');
    insert into books (ISBN, user_id) values ('123456789', '3');
    insert into books (ISBN, user_id) values ('987654321', '4');