apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: bbl
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
      tier: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: redis
        tier: redis
    spec:
      containers:
      - image: redis:7.2.4
        name: redis        
        ports:
        - containerPort: 6379
          name: redis
      #   volumeMounts:
      #   - name: redis-persistent-storage
      #     mountPath: /data
      # volumes:
      # - name: redis-persistent-storage
      #   persistentVolumeClaim:
      #     claimName: redis-pv-claim