apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
  namespace: bbl
  labels:
    app: flaskapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Mi