apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: bbl
  labels:
    app: redis
spec:
 
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
      
  # type: NodePort
  selector:
    app: redis
    # tier: redis
    #clusterIP: None