prometheus:
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    serviceMonitorNamespaceSelector:
      matchExpressions:
      - key: kubernetes.io/metadata.name
        operator: Exists
    ruleSelector:
      matchExpressions:
      - key: prometheus
        operator: In
        values:
        - bbl-rules
    additionalScrapeConfigs:
    - job_name: 'jolie-proxy'
      static_configs:
      - targets: [ "jolie-proxy.bbl:9091" ]
    - job_name: mysql
      static_configs:
      - targets: [ "mysql.bbl:3306" ]
    - job_name: nginx
      static_configs:
      - targets: [ "nginx.bbl" ]
    - job_name: redis
      static_configs:
      - targets: [ "redis.bbl:6379" ]
    - job_name: biblio
      metrics_path: /metrics/
      static_configs:
      - targets: [ "biblio-api.bbl:8084" ]
    - job_name: biblio-app
      metrics_path: /metrics/
      static_configs:
      - targets: [ "biblio-app.bbl:8083" ]
  service:
    annotations: {}
    labels: {}
    clusterIP: ""
    ipDualStack:
      enabled: false
      ipFamilies: [ "IPv6", "IPv4" ]
      ipFamilyPolicy: "PreferDualStack"

    ## Port for Prometheus Service to listen on
    ##
    port: 9090

    ## To be used with a proxy extraContainer port
    targetPort: 9090

    ## Port for Prometheus Reloader to listen on
    ##
    reloaderWebPort: 8080

    ## List of IP addresses at which the Prometheus server service is available
    ## Ref: https://kubernetes.io/docs/user-guide/services/#external-ips
    ##
    externalIPs: []

    ## Port to expose on each node
    ## Only used if service.type is 'NodePort'
    ##
    nodePort: 30090

    ## Loadbalancer IP
    ## Only use if service.type is "LoadBalancer"
    loadBalancerIP: ""
    loadBalancerSourceRanges: []

    ## Denotes if this Service desires to route external traffic to node-local or cluster-wide endpoints
    ##
    externalTrafficPolicy: Cluster

    ## Service type
    ##
    type: NodePort

grafana:
  sidecar:
    datasources:
      defaultDatasourceEnabled: true
  additionalDataSources:
  - name: Elasticsearch
    type: elasticsearch
    url: http://elasticsearch:9200

alertmanager:
  config:
    global:
      resolve_timeout: 5m
    route:
      group_by: [ 'alertname' ]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 10m
      receiver: discord
receivers:
- name: discord
  discord_configs:
  - webhook_url: https://discord.com/api/webhooks/1314296315093581824/c9sEByqjZS5zqS7c9UjDHVJgz3xTNNKV7-i_FNyMyTMgCV83Hsf28PeXQ5LpnuoB4jE2
