apiVersion: v1
kind: ConfigMap
metadata:
  name: jolie-proxy-config
  namespace: bbl
data:
  config.json: |
    {
      "mysql": {
        "host": "mysql-service",
        "port": 3306
      },
      "redis": {
        "host": "redis",
        "port": 6379
      },
      "http": {
        "port": 8090
      },
      "metrics": {
        "port": 9091
      },
      "biblio-app": {
        "host": "biblio-app",
        "port": 8081
      },
      "biblio-api": {
        "host": "biblio-api",
        "port": 8084
      },
      "prometheus": {
        "host": "prometheus",
        "port": 9090
    }
