apiVersion: apps/v1
kind: Deployment
metadata:
  name: jolie-proxy
  namespace: bbl
  labels:
    app: jolie-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jolie-proxy
  template:
    metadata:
      labels:
        app: jolie-proxy
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: jolie-proxy
        image: pjoseph5011/kubescale_jolie_proxy:latest
        imagePullPolicy: Always
        ports: 9091
        