apiVersion: apps/v1
kind: Deployment
metadata:
  name: jolie-proxy
  namespace: bbl
  labels:
    app: jolie-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jolie-proxy
  template:
    metadata:
      labels:
        app: jolie-proxy
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: jolie-proxy
        image: pjoseph5011/kubescale_jolie-proxy:latest
        imagePullPolicy: Always
        ports: 
        - containerPort: 9091
          name: http
        - containerPort: 9092
          name: metrics
        env:
        - name: MYSQL_HOST
          value: "mysql.bbl.svc.cluster.local"
        - name: MYSQL_USER
          value: "root"
        - name: MYSQL_PASSWORD
          value: "password"
        - name: MYSQL_DB
          value: "gestion_bibliotheque" 
        - name: MySQL_PORT
          value: "3306"       
        - name: ALERTMANAGER_URL
          value: "http://alertmanager.monitoring.svc.cluster:9093"
        - name: PROMETHEUS_URL
          value: "http://prometheus.monitoring.svc.cluster:9090"
        