apiVersion: v1
kind: Service
metadata:
  name: jolie-proxy
  namespace: bbl
  labels:
    app: jolie-proxy
spec:
  selector:
    app: jolie-proxy
  ports:  
  - protocol: TCP
    port: 9091
    targetPort: 9091   
  type: ClusterIP
