apiVersion: v1
kind: Service
metadata:
  name: jolie-proxy
  namespace: bbl
  labels:
    app: jolie-proxy
spec:
  selector:
    app: jolie-proxy
  ports:  
  - name: http
    port: 9091
    targetPort: 9091
  - name: metrics
    port: 9092
    targetPort: 9092    
  type: ClusterIP
