apiVersion: v1
kind: Service
metadata:
  name: biblio-app
  namespace: bbl  
spec:  
  selector:
    app: biblio-app 
  ports:
    - port: 8081      
      targetPort: 8081
      name: metrics
    - port: 8083      
      targetPort: 8083
      name: http
  type: ClusterIP  