kind: ConfigMap
apiVersion: v1
metadata:
  name: uwsgi-config
  namespace: bbl
data:
  uwsgi.ini: |
    [uwsgi]
    #WSGI module and Callable app
    virtualenv = /srv/app/public/venv/  
    
    wsgi-file = wsgi.py
    callable = app
    plugin = python
    # maximum number of worker processes
    processes = 4
    threads = 2
    stats = 127.0.0.1:9191
    vaccum = true
    # the socket (use the full path to be safe
    socket = :8080
    # ... with appropriate permissions - may be needed
    chmod-socket    = 664
    # clear environment on exit
    vacuum          = true

    # DO NOT USE IN PRODUCTION
    py-autoreload   = 2
    master = true
    die-on-term = true
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: start-config
data:
  start.sh: |
    #!/bin/bash    
    #rm -rf public
    git clone -b projet3 https://github.com/josephpierres/MGL7760-H2024-Projet1-Groupe-1.git publics
    cp -ra publics/wsgi/* app/
    rm -rf publics 
    cd /app    
    /usr/bin/python3 -m venv venv
    source venv/bin/activate
    pip install flask
    pip install -r requirements.txt
    

   
    # #!/bin/bash
    # cd /srv/app/
    # #rm -rf public
    # git clone -b projet3 https://github.com/josephpierres/MGL7760-H2024-Projet1-Groupe-1.git /srv/app/publics
    # cp -ra publics/k8s/data/wsgi/* public/
    # rm -rf publics 
    # cd /srv/app/public
    # cp -ra wsgi/* .
    # rm -rf wsgi  
    # /usr/bin/python3 -m venv venv
    # source venv/bin/activate
    # pip install flask
    # pip install -r requirements.txt