
FROM mysql:8.3
ARG MYSQL_ROOT_PASSWORD
ARG MYSQL_USER
ARG MYSQL_PASSWORD
ENV MYSQL_ROOT_PASSWORD=password
ENV MYSQL_USER=user
ENV MYSQL_PASSWORD=user
ADD db.sql /docker-entrypoint-initdb.d
# COPY ./conf-file.cnf /etc/mysql/conf.d/conf-file.cnf
RUN apt-get update && apt-get install -y netcat
HEALTHCHECK CMD nc -z localhost 3306
EXPOSE 3306