# 2. Configuration KEDA pour le backend
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: backend-scaler
  namespace: bbl
spec:
  scaleTargetRef:
    name: biblio-api
    kind: Deployment
    apiVersion: apps/v1
  triggers:
  - type: prometheus
    metricType: Value
    metadata:
      serverAddress: http://bibliobservability-kube-pr-prometheus.monitoring.svc.cluster.local:9090
      metricName: jolie_backend_replica
      threshold: '2' # 2 mysql est en ligne, 1 mysql est hors ligne 
      query: jolie_backend_replica{instance="jolie-proxy:9092", job="jolie"}
      ignoreNullValues: 'false'
  minReplicaCount: 1
  maxReplicaCount: 3
  pollingInterval: 5
  cooldownPeriod: 30
