# 1. Configuration KEDA pour le frontend
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-scaledobject
  namespace: bbl
spec:
  scaleTargetRef:
    name: redis
    kind: Deployment
    apiVersion: apps/v1
  triggers:
  - type: prometheus
    metricType: Value
    metadata:
      serverAddress: http://bibliobservability-kube-pr-prometheus.monitoring.svc.cluster.local:9090
      metricName: redis_status
      query: |
        mysql_status
      threshold: "1.5" # Seuil de bascule (Redis passe à 2 si mysql_status ≥ 2)
      ignoreNullValues: 'false'
  minReplicaCount: 1
  maxReplicaCount: 2
  pollingInterval: 10
  cooldownPeriod: 10
