---
# 3. Configuration KEDA pour MySQL
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mysql-scaler
  namespace: bbl
spec:
  scaleTargetRef:
    name: mysql
    kind: Deployment
    apiVersion: apps/v1 # Ajout de l'apiVersion manquant
  triggers:
  - type: prometheus
    metricType: Value
    metadata:
      serverAddress: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      metricName: mysql_slow_queries
      threshold: '400'
      query: |
        sum(rate(mysql_global_status_commands_total{command="select", namespace="bbl"}[1m]))
      ignoreNullValues: 'false'
  minReplicaCount: 1
  maxReplicaCount: 2 # We don't want to have more than 2 replicas
  pollingInterval: 10 # How frequently we should go for metrics (in seconds)
  cooldownPeriod: 60 # How many seconds should we wait for downscale
